"""Deterministic TOML emitter for cppup package.toml manifests.

`tomli_w` doesn't pin key order, and we need byte-stable output so that
regenerating the same recipe twice yields identical bytes (the CI
diff-guard depends on this). The emitter sidesteps `tomli_w` and renders
each section in a canonical order with sorted keys.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any

SECTION_ORDER: tuple[str, ...] = (
    "package",
    "source",
    "build",
    "toolchain",
    "plugin",
    "features",
    "dependencies",
    "build-dependencies",
    "test-dependencies",
    "exports",
    "platforms",
)

_PACKAGE_KEY_ORDER: tuple[str, ...] = (
    "name",
    "version",
    "kind",
    "description",
    "license",
    "homepage",
    "repository",
    "cppup_compat",
)

_SOURCE_KEY_ORDER: tuple[str, ...] = (
    "type",
    "url",
    "tag",
    "branch",
    "commit",
    "subdirectory",
    "checksum",
)

_FEATURE_KEY_ORDER: tuple[str, ...] = ("type", "default", "values", "description")

_EXPORT_KEY_ORDER: tuple[str, ...] = (
    "type",
    "name",
    "install_as",
    "link_name",
    "include_paths",
    "lib_paths",
    "link_flags",
    "system_libs",
    "frameworks",
    "requires_internal",
)

_PATCH_KEY_ORDER: tuple[str, ...] = ("url", "sha256", "description", "strip")

_BUILD_KEY_ORDER: tuple[str, ...] = ("system", "args")
_PLATFORMS_KEY_ORDER: tuple[str, ...] = ("os", "arch")


def emit_toml(data: Mapping[str, Any], todos: Iterable[str] | None = None) -> str:
    for required in ("schema", "package"):
        if required not in data:
            raise ValueError(f"missing required top-level key: {required}")

    parts: list[str] = ["# Generated by conan2toml. Do not hand-edit; regenerate from upstream",
                       "# conanfile.py instead."]

    todo_list = list(todos) if todos else []
    if todo_list:
        parts.append("#")
        parts.append("# TODO(conan2toml): manual review needed for:")
        parts.extend(f"#   - {item}" for item in todo_list)

    parts.append(f"schema = {_scalar(data['schema'])}")
    parts.append("")

    for section in SECTION_ORDER:
        body = data.get(section)
        if body is None:
            continue
        rendered = _render_section(section, body)
        if rendered is None:
            continue
        parts.append(rendered)

    out = "\n".join(parts).rstrip() + "\n"
    return out


def _render_section(name: str, body: Any) -> str | None:
    if name == "exports":
        return _render_array_of_tables(name, body)
    if name in ("dependencies", "build-dependencies", "test-dependencies"):
        if not body:
            return None
        return _render_string_map(name, body)
    if name == "features":
        if not body:
            return None
        return _render_features(body)
    if name == "source":
        return _render_source(body)
    if name == "package":
        return _render_table(name, body, _PACKAGE_KEY_ORDER)
    if name == "build":
        return _render_table(name, body, _BUILD_KEY_ORDER)
    if name == "toolchain":
        return _render_table(name, body)
    if name == "platforms":
        return _render_table(name, body, _PLATFORMS_KEY_ORDER)
    if name == "plugin":
        return _render_plugin(body)
    return _render_table(name, body)


def _render_table(name: str, body: Mapping[str, Any], key_order: Iterable[str] = ()) -> str:
    keys = list(key_order)
    seen = set(keys)
    keys.extend(sorted(k for k in body if k not in seen))
    lines = [f"[{name}]"]
    for key in keys:
        if key not in body:
            continue
        lines.append(f"{key} = {_scalar(body[key])}")
    lines.append("")
    return "\n".join(lines)


def _render_source(body: Mapping[str, Any]) -> str:
    patches = body.get("patches")
    base = {k: v for k, v in body.items() if k != "patches"}
    out = _render_table("source", base, _SOURCE_KEY_ORDER)
    if patches:
        out += "\n" + _render_array_of_tables("source.patches", patches, _PATCH_KEY_ORDER)
    return out


def _render_features(body: Mapping[str, Any]) -> str:
    lines = ["[features]"]
    for key in sorted(body):
        spec = body[key]
        inline = _inline_table(spec, _FEATURE_KEY_ORDER)
        lines.append(f"{key} = {inline}")
    lines.append("")
    return "\n".join(lines)


def _render_string_map(name: str, body: Mapping[str, Any]) -> str:
    lines = [f"[{name}]"]
    for key in sorted(body):
        value = body[key]
        if isinstance(value, Mapping):
            lines.append(f"{key} = {_inline_table(value)}")
        else:
            lines.append(f"{key} = {_scalar(value)}")
    lines.append("")
    return "\n".join(lines)


def _render_array_of_tables(
    name: str,
    items: Iterable[Mapping[str, Any]],
    key_order: Iterable[str] = (),
) -> str:
    keys = list(key_order) or list(_EXPORT_KEY_ORDER)
    parts: list[str] = []
    for item in items:
        parts.append(f"[[{name}]]")
        seen = set(keys)
        ordered = [k for k in keys if k in item]
        ordered.extend(sorted(k for k in item if k not in seen))
        for k in ordered:
            parts.append(f"{k} = {_scalar(item[k])}")
        parts.append("")
    return "\n".join(parts)


def _render_plugin(body: Mapping[str, Any]) -> str:
    base = {k: v for k, v in body.items() if k not in ("entries", "dependencies")}
    out = _render_table("plugin", base)
    entries = body.get("entries") or []
    if entries:
        out += _render_array_of_tables("plugin.entries", entries)
    deps = body.get("dependencies")
    if deps:
        out += _render_table("plugin.dependencies", deps)
    return out


def _inline_table(body: Mapping[str, Any], key_order: Iterable[str] = ()) -> str:
    keys = list(key_order)
    seen = set(keys)
    keys.extend(sorted(k for k in body if k not in seen))
    items = [f"{k} = {_scalar(body[k])}" for k in keys if k in body]
    return "{ " + ", ".join(items) + " }"


def _scalar(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return '""'
    if isinstance(value, str):
        return _toml_string(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_scalar(v) for v in value) + "]"
    if isinstance(value, Mapping):
        return _inline_table(value)
    raise TypeError(f"unsupported value type: {type(value).__name__}")


def _toml_string(value: str) -> str:
    if "\n" in value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
