// AUTOGENERATED by scripts/embed_init_templates.sh -- DO NOT EDIT BY HAND.
// Source of truth lives in templates/init/.
#pragma once

#include <array>
#include <string_view>

namespace cppup::cli::init_templates
{

struct Entry
{
  std::string_view category;
  std::string_view rel_path;
  std::string_view content;
};

inline constexpr std::array kEntries = {
    Entry{"common", ".clang-format", R"CPPUPTPL(BasedOnStyle: Google
Standard: Latest
IndentWidth: 2
ColumnLimit: 100
PointerAlignment: Left
NamespaceIndentation: None
)CPPUPTPL"},
    Entry{"common", ".gitignore", R"CPPUPTPL(# Build artifacts
build/
.cppup/cache/
compile_commands.json
.cache/

# Compiled artifacts
*.o
*.obj
*.exe
*.so
*.dylib
*.a

# Coverage
*.gcov
*.gcda
*.gcno

# IDE / editor
.idea/
*.swp
)CPPUPTPL"},
    Entry{"common", "README.md", R"CPPUPTPL(# __PROJECT_NAME__

A C++23 project managed with [cppup](https://gitlab.com/and-elf/cppup).

## Build

```bash
cppup build
cppup test
cppup format
```
)CPPUPTPL"},
    Entry{"common", "build.cpp", R"CPPUPTPL(#include <cppup/configuration.hpp>

using namespace cppup::configuration;

extern "C" BuildConfiguration configure()
{
  BuildConfiguration config;

  config.toolchain     = Toolchain{"g++"};
  config.compile_flags = {Flag{"-Wall"}, Flag{"-Wextra"}, Flag{"-Wpedantic"}, Flag{"-std=c++23"}};
  config.include_paths = {"include", "src"};

  config.binaries = {Binary{"__PROJECT_NAME__", {"src/main.cpp"}}};

  config.tests = {Test{"unit_tests", {"tests/test_main.cpp"}}};
  config.tests.back().link_flags = {Flag{"-lgtest"}, Flag{"-lgtest_main"}, Flag{"-lpthread"}};

  return config;
}
)CPPUPTPL"},
    Entry{"common", "src/main.cpp", R"CPPUPTPL(#include <print>

int main()
{
  std::println("Hello from __PROJECT_NAME__!");
  return 0;
}
)CPPUPTPL"},
    Entry{"common", "tests/test_main.cpp", R"CPPUPTPL(#include <gtest/gtest.h>

TEST(Smoke, BasicArithmetic)
{
  EXPECT_EQ(2 + 2, 4);
}
)CPPUPTPL"},
    Entry{"devcontainer", ".devcontainer/devcontainer.json", R"CPPUPTPL({
    "name": "__PROJECT_NAME__",
    "build": {
        "dockerfile": "../Dockerfile"
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "llvm-vs-code-extensions.vscode-clangd",
                "vadimcn.vscode-lldb",
                "matepek.vscode-catch2-test-adapter",
                "xaver.clang-format"
            ]
        }
    },
    "remoteUser": "vscode",
    "workspaceFolder": "/workspaces/__PROJECT_NAME__"
}
)CPPUPTPL"},
    Entry{"docker", "Dockerfile", R"CPPUPTPL(FROM debian:trixie-slim

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        g++ \
        clang \
        clang-tidy \
        clang-format \
        clangd \
        lldb \
        gdb \
        git \
        ca-certificates \
        libsqlite3-dev \
        libssl-dev \
        libgtest-dev \
        libgmock-dev \
        sudo \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID --shell /bin/bash --create-home $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
WORKDIR /workspaces/__PROJECT_NAME__
)CPPUPTPL"},
    Entry{"gitlab", ".gitlab-ci.yml", R"CPPUPTPL(image: debian:trixie-slim

stages:
  - build
  - test
  - lint

before_script:
  - apt-get update -qq && apt-get install -y --no-install-recommends
      build-essential g++ clang clang-tidy clang-format
      libsqlite3-dev libssl-dev libgtest-dev libgmock-dev
      ca-certificates git
  - command -v cppup >/dev/null || (echo "cppup not installed in image" && exit 1)

build:
  stage: build
  script:
    - cppup build
  artifacts:
    paths:
      - build/
    expire_in: 1 day

test:
  stage: test
  needs: ["build"]
  script:
    - cppup test

format:
  stage: lint
  script:
    - cppup format --check

tidy:
  stage: lint
  needs: ["build"]
  script:
    - cppup tidy
  allow_failure: true
)CPPUPTPL"},
    Entry{"vscode", ".vscode/extensions.json", R"CPPUPTPL({
    "recommendations": [
        "llvm-vs-code-extensions.vscode-clangd",
        "vadimcn.vscode-lldb",
        "matepek.vscode-catch2-test-adapter",
        "xaver.clang-format"
    ]
}
)CPPUPTPL"},
    Entry{"vscode", ".vscode/launch.json", R"CPPUPTPL({
    "version": "0.2.0",
    "inputs": [
        {
            "id": "gtestFilter",
            "type": "promptString",
            "description": "GoogleTest filter (e.g. Smoke.* or *.BasicArithmetic)",
            "default": "*"
        }
    ],
    "configurations": [
        {
            "name": "Debug __PROJECT_NAME__",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/build/__PROJECT_NAME__",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "cppup: build"
        },
        {
            "name": "Debug current test file",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/build/tests/${fileBasenameNoExtension}",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "cppup: build"
        },
        {
            "name": "Debug current test file (filter case)",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/build/tests/${fileBasenameNoExtension}",
            "args": ["--gtest_filter=${input:gtestFilter}", "--gtest_break_on_failure"],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "cppup: build"
        }
    ]
}
)CPPUPTPL"},
    Entry{"vscode", ".vscode/settings.json", R"CPPUPTPL({
    "C_Cpp.intelliSenseEngine": "disabled",
    "C_Cpp.autocomplete": "disabled",
    "C_Cpp.errorSquiggles": "disabled",
    "clangd.arguments": [
        "--background-index",
        "--clang-tidy",
        "--header-insertion=never",
        "--completion-style=detailed",
        "--pch-storage=memory",
        "--compile-commands-dir=${workspaceFolder}"
    ],
    "clangd.checkUpdates": false,
    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "build/tests/test_*",
            "cwd": "${workspaceFolder}",
            "framework": {
                "gtest": {
                    "testGrouping": {
                        "groupBySource": {}
                    }
                }
            },
            "runTask": {
                "before": [
                    "cppup: build"
                ]
            }
        }
    ],
    "testMate.cpp.test.executableCleanup": false,
    "testMate.cpp.discovery.runtimeLimit": 30,
    "testMate.cpp.test.parallelExecutionOfExecutableLimit": 4,
    "testMate.cpp.debug.configTemplate": {
        "type": "lldb",
        "MIMode": "lldb",
        "request": "launch",
        "program": "${exec}",
        "args": "${argsArray}",
        "cwd": "${cwd}",
        "env": "${envObj}",
        "sourceFileMap": "${sourceFileMapObj}"
    }
}
)CPPUPTPL"},
    Entry{"vscode", ".vscode/tasks.json", R"CPPUPTPL({
    "version": "2.0.0",
    "tasks": [
        {
            "label": "cppup: build",
            "type": "shell",
            "command": "cppup",
            "args": ["build"],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": ["$gcc"],
            "presentation": {
                "reveal": "silent",
                "panel": "dedicated"
            }
        },
        {
            "label": "cppup: build (asan)",
            "type": "shell",
            "command": "cppup",
            "args": ["build", "--asan"],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "group": "build",
            "problemMatcher": ["$gcc"]
        },
        {
            "label": "cppup: test",
            "type": "shell",
            "command": "cppup",
            "args": ["test"],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "dependsOn": "cppup: build",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "problemMatcher": []
        }
    ]
}
)CPPUPTPL"},
};

}  // namespace cppup::cli::init_templates
