#include "lockfile.hpp"

#include <algorithm>
#include <array>
#include <map>
#include <set>
#include <sstream>
#include <utility>

#include "../../configuration/types.hpp"

namespace cppup::cli::lockfile
{

namespace
{

namespace conf = cppup::configuration;

constexpr std::string_view k_header_line1 = "# cppup.lock - DO NOT EDIT";
constexpr std::string_view k_header_line2 =
    "# Generated by `cppup package lock`. Run `cppup package sync` to reproduce.";

constexpr std::array<std::pair<SourceKind, std::string_view>, 6> k_source_kind_names{{
    {SourceKind::Registry, "registry"},
    {SourceKind::Git, "git"},
    {SourceKind::Directory, "directory"},
    {SourceKind::Url, "url"},
    {SourceKind::Tar, "tar"},
    {SourceKind::Zip, "zip"},
}};

SourceKind map_source_type(conf::SourceType type) noexcept
{
  switch (type)
  {
    case conf::SourceType::DIRECTORY:
      return SourceKind::Directory;
    case conf::SourceType::GIT:
      return SourceKind::Git;
    case conf::SourceType::TAR:
      return SourceKind::Tar;
    case conf::SourceType::ZIP:
      return SourceKind::Zip;
    case conf::SourceType::HTTP:
      return SourceKind::Url;
    case conf::SourceType::REGISTRY:
      return SourceKind::Registry;
  }
  return SourceKind::Registry;
}

// Backslash-escape `\` and `"` so the resulting string can be safely
// wrapped in double quotes. The serializer always wraps every string in
// quotes (including empty), so the parser can detect missing values
// without ambiguity.
std::string quote(std::string_view value)
{
  std::string out;
  out.reserve(value.size() + 2);
  out.push_back('"');
  for (const char chr : value)
  {
    if (chr == '\\' || chr == '"')
    {
      out.push_back('\\');
    }
    out.push_back(chr);
  }
  out.push_back('"');
  return out;
}

[[nodiscard]] std::expected<std::string, std::string> unquote(std::string_view value)
{
  if (value.size() < 2 || value.front() != '"' || value.back() != '"')
  {
    return std::unexpected("expected quoted string");
  }
  std::string out;
  out.reserve(value.size() - 2);
  for (std::size_t i = 1; i + 1 < value.size(); ++i)
  {
    if (value[i] == '\\' && i + 2 < value.size())
    {
      out.push_back(value[++i]);
      continue;
    }
    out.push_back(value[i]);
  }
  return out;
}

std::string serialize_string_array(const std::vector<std::string>& values)
{
  std::string out = "[";
  for (std::size_t i = 0; i < values.size(); ++i)
  {
    if (i != 0)
    {
      out += ", ";
    }
    out += quote(values[i]);
  }
  out += ']';
  return out;
}

// Trim ASCII whitespace from both ends. Used to make the parser tolerant
// of indentation and trailing CR on Windows-saved files.
std::string_view trim(std::string_view text) noexcept
{
  while (!text.empty() && (text.front() == ' ' || text.front() == '\t' || text.front() == '\r'))
  {
    text.remove_prefix(1);
  }
  while (!text.empty() && (text.back() == ' ' || text.back() == '\t' || text.back() == '\r'))
  {
    text.remove_suffix(1);
  }
  return text;
}

[[nodiscard]] std::expected<std::vector<std::string>, std::string> parse_string_array(
    std::string_view value)
{
  if (value.size() < 2 || value.front() != '[' || value.back() != ']')
  {
    return std::unexpected("expected '[' ... ']' for array");
  }
  std::vector<std::string> out;
  value.remove_prefix(1);
  value.remove_suffix(1);
  value = trim(value);
  while (!value.empty())
  {
    if (value.front() != '"')
    {
      return std::unexpected("array element must be a quoted string");
    }
    // Find the matching closing quote, respecting backslash escapes.
    std::size_t end = 1;
    while (end < value.size() && value[end] != '"')
    {
      if (value[end] == '\\' && end + 1 < value.size())
      {
        end += 2;
        continue;
      }
      ++end;
    }
    if (end >= value.size())
    {
      return std::unexpected("unterminated string in array");
    }
    auto element = unquote(value.substr(0, end + 1));
    if (!element)
    {
      return std::unexpected(element.error());
    }
    out.push_back(std::move(*element));
    value.remove_prefix(end + 1);
    value = trim(value);
    if (value.empty())
    {
      break;
    }
    if (value.front() != ',')
    {
      return std::unexpected("expected ',' between array elements");
    }
    value.remove_prefix(1);
    value = trim(value);
  }
  return out;
}

void write_entry(std::ostringstream& output, const Entry& entry)
{
  output << "[[package]]\n";
  output << "name = " << quote(entry.name) << '\n';
  output << "version = " << quote(entry.version) << '\n';
  output << "source = " << quote(to_string(entry.source)) << '\n';
  output << "url = " << quote(entry.url) << '\n';
  output << "git_branch = " << quote(entry.git_branch) << '\n';
  output << "git_commit = " << quote(entry.git_commit) << '\n';
  output << "subdirectory = " << quote(entry.subdirectory) << '\n';
  output << "build_system = " << quote(entry.build_system) << '\n';
  output << "checksum = " << quote(entry.checksum) << '\n';
  output << "dependencies = " << serialize_string_array(entry.dependencies) << '\n';
}

// One parsed `key = value` pair plus the source line for diagnostics.
// Bundled so the line-splitting can return a single value through
// `std::expected` instead of an out-param.
struct KeyValueLine
{
  std::string_view key;
  std::string_view value;
  std::size_t      line_no;
};

[[nodiscard]] std::expected<KeyValueLine, std::string> split_key_value(std::string_view line,
                                                                       std::size_t      line_no)
{
  const auto eq_token = line.find('=');
  if (eq_token == std::string_view::npos)
  {
    return std::unexpected("line " + std::to_string(line_no) + ": expected 'key = value'");
  }
  return KeyValueLine{
      .key     = trim(line.substr(0, eq_token)),
      .value   = trim(line.substr(eq_token + 1)),
      .line_no = line_no,
  };
}

// Top-level `version = N` check. Returns `true` if the line was the
// recognized version key; unknown top-level keys are silently ignored for
// forward compatibility.
[[nodiscard]] std::expected<bool, std::string> apply_top_level(const KeyValueLine& line)
{
  if (line.key != "version")
  {
    return false;
  }
  try
  {
    const int parsed = std::stoi(std::string(line.value));
    if (parsed != k_format_version)
    {
      return std::unexpected("unsupported lockfile version: " + std::to_string(parsed));
    }
  }
  catch (const std::exception&)
  {
    return std::unexpected("line " + std::to_string(line.line_no) +
                           ": invalid version: " + std::string(line.value));
  }
  return true;
}

// Map of string-valued per-package keys to their target member in `Entry`.
// Keeps the per-key dispatch out of `parse_package_line` so the parser's
// cognitive-complexity stays well under the lint threshold.
using StringFieldTable = std::map<std::string_view, std::string Entry::*>;
const StringFieldTable& string_fields()
{
  static const StringFieldTable table{
      {"name", &Entry::name},
      {"version", &Entry::version},
      {"url", &Entry::url},
      {"git_branch", &Entry::git_branch},
      {"git_commit", &Entry::git_commit},
      {"subdirectory", &Entry::subdirectory},
      {"build_system", &Entry::build_system},
      {"checksum", &Entry::checksum},
  };
  return table;
}

[[nodiscard]] std::expected<void, std::string> apply_string_field(Entry&      entry,
                                                                  std::string Entry::* member,
                                                                  const KeyValueLine&  line)
{
  auto unquoted = unquote(line.value);
  if (!unquoted)
  {
    return std::unexpected("line " + std::to_string(line.line_no) + ": " + unquoted.error());
  }
  entry.*member = std::move(*unquoted);
  return {};
}

[[nodiscard]] std::expected<void, std::string> apply_source_field(Entry&              entry,
                                                                  const KeyValueLine& line)
{
  auto unquoted = unquote(line.value);
  if (!unquoted)
  {
    return std::unexpected("line " + std::to_string(line.line_no) + ": " + unquoted.error());
  }
  auto kind = parse_source_kind(*unquoted);
  if (!kind)
  {
    return std::unexpected("line " + std::to_string(line.line_no) + ": " + kind.error());
  }
  entry.source = *kind;
  return {};
}

[[nodiscard]] std::expected<void, std::string> apply_dependencies_field(Entry&              entry,
                                                                        const KeyValueLine& line)
{
  auto array = parse_string_array(line.value);
  if (!array)
  {
    return std::unexpected("line " + std::to_string(line.line_no) + ": " + array.error());
  }
  entry.dependencies = std::move(*array);
  return {};
}

[[nodiscard]] std::expected<void, std::string> apply_package_line(Entry&              entry,
                                                                  const KeyValueLine& line)
{
  const auto& fields = string_fields();
  if (const auto field = fields.find(line.key); field != fields.end())
  {
    return apply_string_field(entry, field->second, line);
  }
  if (line.key == "source")
  {
    return apply_source_field(entry, line);
  }
  if (line.key == "dependencies")
  {
    return apply_dependencies_field(entry, line);
  }
  // Forward-compatible: unknown per-package keys are ignored.
  return {};
}

}  // namespace

std::string_view to_string(SourceKind kind) noexcept
{
  for (const auto& [candidate, name] : k_source_kind_names)
  {
    if (candidate == kind)
    {
      return name;
    }
  }
  return "registry";
}

std::expected<SourceKind, std::string> parse_source_kind(std::string_view text) noexcept
{
  for (const auto& [candidate, name] : k_source_kind_names)
  {
    if (name == text)
    {
      return candidate;
    }
  }
  return std::unexpected(std::string("unknown source kind: ") + std::string(text));
}

std::string serialize(const std::vector<Entry>& entries)
{
  std::vector<Entry> sorted = entries;
  std::ranges::sort(sorted, [](const Entry& lhs, const Entry& rhs) { return lhs.name < rhs.name; });

  std::ostringstream output;
  output << k_header_line1 << '\n';
  output << k_header_line2 << '\n';
  output << "version = " << k_format_version << '\n';
  for (const auto& entry : sorted)
  {
    output << '\n';
    write_entry(output, entry);
  }
  return output.str();
}

std::expected<std::vector<Entry>, std::string> parse(std::string_view content)
{
  std::vector<Entry>   entries;
  std::optional<Entry> current;
  bool                 saw_version = false;

  const auto flush = [&]
  {
    if (current)
    {
      entries.push_back(std::move(*current));
      current.reset();
    }
  };

  std::size_t line_no = 0;
  std::size_t pos     = 0;
  while (pos <= content.size())
  {
    const std::size_t      next = content.find('\n', pos);
    const std::string_view raw =
        content.substr(pos, next == std::string_view::npos ? content.size() - pos : next - pos);
    pos = (next == std::string_view::npos) ? content.size() + 1 : next + 1;
    ++line_no;
    const auto line = trim(raw);
    if (line.empty() || line.front() == '#')
    {
      continue;
    }
    if (line == "[[package]]")
    {
      flush();
      current = Entry{};
      continue;
    }

    auto split = split_key_value(line, line_no);
    if (!split)
    {
      return std::unexpected(split.error());
    }
    if (!current)
    {
      auto top = apply_top_level(*split);
      if (!top)
      {
        return std::unexpected(top.error());
      }
      saw_version = saw_version || *top;
      continue;
    }
    if (auto applied = apply_package_line(*current, *split); !applied)
    {
      return std::unexpected(applied.error());
    }
  }
  flush();

  if (!saw_version)
  {
    return std::unexpected("missing 'version' header");
  }
  return entries;
}

namespace
{

// Convert one PackageInfo into a lockfile Entry. The dep-graph walker
// fills `entry.dependencies` separately from the direct children's names
// before pushing the entry into the result vector.
Entry entry_from_info(const conf::PackageInfo& info)
{
  Entry entry;
  entry.name         = info.name;
  entry.version      = info.version.value_or("");
  entry.source       = map_source_type(info.source_type);
  entry.url          = info.url.value_or("");
  entry.git_branch   = info.git_branch.value_or("");
  entry.git_commit   = info.git_commit.value_or("");
  entry.subdirectory = info.subdirectory.value_or("");
  if (entry.source == SourceKind::Directory && entry.url.empty())
  {
    entry.url = info.source_directory.value_or("");
  }
  entry.dependencies.reserve(info.dependencies.size());
  for (const auto& dep : info.dependencies)
  {
    entry.dependencies.push_back(dep.name);
  }
  return entry;
}

// Mutable state threaded through the recursive DFS. `done` is the set of
// names already emitted (dedup by name; first occurrence wins). `stack`
// is the names currently on the recursion stack - revisiting a name in
// `stack` is a cycle and must error rather than recurse forever.
struct WalkState
{
  std::vector<Entry>    entries;
  std::set<std::string> done;
  std::set<std::string> stack;
};

// DFS over the manifest dep graph. Recursion is natural here; cycles are
// caught explicitly via `state.stack` before the recursive call returns.
// NOLINTNEXTLINE(misc-no-recursion)
[[nodiscard]] std::expected<void, std::string> walk_info(const conf::PackageInfo& info,
                                                         WalkState&               state)
{
  if (state.done.contains(info.name))
  {
    return {};
  }
  if (!state.stack.insert(info.name).second)
  {
    return std::unexpected("dependency cycle detected at package: " + info.name);
  }
  for (const auto& dep : info.dependencies)
  {
    if (auto child = walk_info(dep, state); !child)
    {
      return child;
    }
  }
  state.stack.erase(info.name);
  state.done.insert(info.name);
  state.entries.push_back(entry_from_info(info));
  return {};
}

}  // namespace

std::expected<std::vector<Entry>, std::string> entries_from_configuration(
    const conf::BuildConfiguration& config)
{
  WalkState state;
  for (const auto& pkg : config.packages)
  {
    if (auto walked = walk_info(pkg.info(), state); !walked)
    {
      return std::unexpected(walked.error());
    }
  }
  std::ranges::sort(state.entries,
                    [](const Entry& lhs, const Entry& rhs) { return lhs.name < rhs.name; });
  return std::move(state.entries);
}

}  // namespace cppup::cli::lockfile
