#!/usr/bin/env bash
#
# Concatenate the public configuration header and its internal dependencies
# into one self-contained header, written to "$1" (default
# build/cppup/configuration.hpp). The output is what `cppup build` materializes
# into a user project's .cppup/include/cppup/configuration.hpp so their
# build.cpp can `#include <cppup/configuration.hpp>` without us shipping the
# header through `update`.
#
# Source of truth stays in src/core/configuration/*.hpp + include/cppup/
# configuration.hpp; this script is rerun by bootstrap.sh and by the top-level
# build.cpp before compilation so the embedded bytes always match.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-${ROOT}/build/generated/cppup/configuration.hpp}"
SRC_DIR="${ROOT}/src/core/configuration"
PUB_DIR="${ROOT}/include/cppup"

# Dependency order: anything that includes types.hpp must come after it, etc.
# The top-level shim (configuration.hpp) goes last and contributes only its
# top-of-file doc comments — its internal `#include "..."` lines are stripped.
# panic.hpp must come first: types.hpp uses CPPUP_CHECK and its quoted
# `#include "../panic.hpp"` is stripped by the amalgamation pass below.
FILES=(
    "${ROOT}/src/core/panic.hpp"
    "${SRC_DIR}/types.hpp"
    "${SRC_DIR}/subproject.hpp"
    "${SRC_DIR}/profile.hpp"
    "${SRC_DIR}/toolchain_flags.hpp"
    "${SRC_DIR}/outputs.hpp"
    "${SRC_DIR}/platform.hpp"
    "${SRC_DIR}/build_configuration.hpp"
    "${SRC_DIR}/runtime.hpp"
    "${PUB_DIR}/configuration.hpp"
)

for f in "${FILES[@]}"; do
    if [[ ! -f "${f}" ]]; then
        echo "FATAL: missing source: ${f}" >&2
        exit 1
    fi
done

mkdir -p "$(dirname "${OUT}")"

{
    cat <<'EOF'
// AUTOGENERATED amalgamation of include/cppup/configuration.hpp and its
// transitive dependencies under src/core/configuration/. DO NOT EDIT BY HAND.
// Regenerate via scripts/amalgamate_configuration_header.sh.
//
// cppup ships this single self-contained header to user projects at
// .cppup/include/cppup/configuration.hpp on every `cppup build`, so their
// build.cpp can `#include <cppup/configuration.hpp>` without us shipping
// the public header through `cppup update`.
#pragma once

EOF

    for f in "${FILES[@]}"; do
        printf '\n// ===== %s =====\n' "$(basename "${f}")"
        # Strip `#pragma once` (we emit one at the top) and quoted internal
        # `#include "..."` lines (their content is inlined below/above).
        # System `#include <...>` lines are left alone — they're idempotent.
        sed -E '/^[[:space:]]*#pragma once[[:space:]]*$/d; /^[[:space:]]*#include[[:space:]]+"[^"]+"[[:space:]]*$/d' "${f}"
    done
} > "${OUT}"

echo "wrote ${OUT}"

# Also emit a portable byte-list include next to the header. `#embed` would
# be the natural way to bake these bytes into the binary, but it needs
# GCC 15 / Clang 19; Debian 13 still ships GCC 14. embedded_configuration_
# header.hpp #includes this file inside an array initializer instead, so the
# content must be a bare comma-separated list of integer byte values (a
# trailing comma is fine in a C++ initializer). Regenerated in lockstep with
# the header above so the embedded bytes always match the on-disk file.
BYTES_OUT="$(dirname "${OUT}")/configuration_bytes.inc"
od -An -v -tu1 "${OUT}" | tr -s ' ' '\n' | grep -v '^$' | sed 's/$/,/' > "${BYTES_OUT}"

echo "wrote ${BYTES_OUT}"
