#!/usr/bin/env bash
#
# Embed templates/init/** into src/core/cli/commands/init_templates_data.hpp
# as a constexpr std::array<Entry, N>. The generated header is tracked in git
# so the bootstrap step (which compiles cppup with plain g++) does not need
# to know about the codegen.
#
# Re-run after editing anything under templates/init/.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES_DIR="${ROOT}/templates/init"
OUT="${ROOT}/src/core/cli/commands/init_templates_data.hpp"
DELIM="CPPUPTPL"

if [[ ! -d "${TEMPLATES_DIR}" ]]; then
    echo "FATAL: templates dir not found: ${TEMPLATES_DIR}" >&2
    exit 1
fi

# Raw string literal closes on the sequence ")<DELIM>". Bail loud if any
# template file contains that sequence so we never silently truncate content.
if grep -r -l ")${DELIM}" "${TEMPLATES_DIR}" >/dev/null 2>&1; then
    echo "FATAL: a template file contains the literal raw-string terminator ')${DELIM}'" >&2
    grep -r -l ")${DELIM}" "${TEMPLATES_DIR}" >&2
    exit 1
fi

emit_entry() {
    local file="$1"
    local rel_to_templates="${file#${TEMPLATES_DIR}/}"
    local category="${rel_to_templates%%/*}"
    local sub="${rel_to_templates#*/}"
    local rel_path

    case "${category}" in
        common)       rel_path="${sub}";;
        vscode)       rel_path=".vscode/${sub}";;
        devcontainer) rel_path=".devcontainer/${sub}";;
        docker)       rel_path="${sub}";;
        gitlab)       rel_path="${sub}";;
        *)
            echo "FATAL: unknown template category '${category}' (from ${file})" >&2
            exit 1
            ;;
    esac

    printf '    Entry{"%s", "%s", R"%s(' "${category}" "${rel_path}" "${DELIM}"
    cat "${file}"
    printf ')%s"},\n' "${DELIM}"
}

{
    cat <<EOF
// AUTOGENERATED by scripts/embed_init_templates.sh -- DO NOT EDIT BY HAND.
// Source of truth lives in templates/init/.
#pragma once

#include <array>
#include <string_view>

namespace cppup::cli::init_templates
{

struct Entry
{
  std::string_view category;
  std::string_view rel_path;
  std::string_view content;
};

inline constexpr std::array kEntries = {
EOF

    while IFS= read -r -d '' f; do
        emit_entry "${f}"
    done < <(find "${TEMPLATES_DIR}" -type f -print0 | LC_ALL=C sort -z)

    cat <<EOF
};

}  // namespace cppup::cli::init_templates
EOF
} > "${OUT}"

echo "wrote ${OUT}"
