from __future__ import annotations

import tomllib

import pytest

from conan2toml.emitter import emit_toml


def test_emitter_round_trips_through_tomllib():
    data = {
        "schema": 1,
        "package": {
            "name": "fmt",
            "version": "10.2.1",
            "kind": "library",
            "license": "MIT",
        },
    }
    out = emit_toml(data)
    parsed = tomllib.loads(out)
    assert parsed == data


def test_emitter_emits_top_level_schema_before_tables():
    data = {
        "package": {"name": "x", "version": "1"},
        "schema": 1,
    }
    out = emit_toml(data)
    schema_idx = out.index("schema")
    package_idx = out.index("[package]")
    assert schema_idx < package_idx


def test_emitter_emits_canonical_section_order():
    data = {
        "platforms": {"os": ["linux"]},
        "build": {"system": "cmake", "args": []},
        "source": {"type": "git", "url": "u", "tag": "t"},
        "package": {"name": "x", "version": "1", "kind": "library"},
        "schema": 1,
    }
    out = emit_toml(data)
    order = [out.index(tag) for tag in ("[package]", "[source]", "[build]", "[platforms]")]
    assert order == sorted(order)


def test_emitter_is_byte_stable_across_calls():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1.0"},
        "features": {
            "shared": {"default": False, "description": "..."},
            "fPIC": {"default": True, "description": "..."},
        },
    }
    a = emit_toml(data)
    b = emit_toml(data)
    assert a == b


def test_emitter_sorts_feature_keys_for_determinism():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "features": {
            "zebra": {"default": False, "description": "z"},
            "alpha": {"default": True, "description": "a"},
        },
    }
    out = emit_toml(data)
    assert out.index("alpha") < out.index("zebra")


def test_emitter_renders_inline_feature_table():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "features": {"shared": {"default": False, "description": "Build as shared"}},
    }
    out = emit_toml(data)
    assert 'shared = { default = false, description = "Build as shared" }' in out


def test_emitter_renders_exports_as_array_of_tables():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "exports": [
            {"type": "library", "name": "z", "include_paths": ["include"]},
        ],
    }
    out = emit_toml(data)
    assert "[[exports]]" in out


def test_emitter_renders_patches_as_array_of_tables():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "source": {
            "type": "tar",
            "url": "u",
            "checksum": "sha256:x",
            "patches": [
                {"url": "https://x/p.patch", "sha256": "abc", "description": "d", "strip": 1},
            ],
        },
    }
    out = emit_toml(data)
    assert "[[source.patches]]" in out


def test_emitter_skips_empty_optional_tables():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "dependencies": {},
        "build-dependencies": {},
    }
    out = emit_toml(data)
    assert "[dependencies]" not in out
    assert "[build-dependencies]" not in out


def test_emitter_keeps_dependencies_when_nonempty():
    data = {
        "schema": 1,
        "package": {"name": "z", "version": "1"},
        "dependencies": {"openssl": ">=3.0"},
    }
    out = emit_toml(data)
    assert "[dependencies]" in out
    assert 'openssl = ">=3.0"' in out


def test_emitter_emits_header_comment():
    data = {"schema": 1, "package": {"name": "z", "version": "1"}}
    out = emit_toml(data)
    assert out.startswith("# Generated by conan2toml")


def test_emitter_emits_todo_block_when_provided():
    data = {"schema": 1, "package": {"name": "z", "version": "1"}}
    out = emit_toml(data, todos=["build(): custom cmake flags", "package_info(): conditional libs"])
    assert "TODO(conan2toml)" in out
    assert "build(): custom cmake flags" in out
    assert "package_info(): conditional libs" in out


@pytest.mark.parametrize("missing", ["schema", "package"])
def test_emitter_rejects_missing_required_top_level_keys(missing):
    data = {"schema": 1, "package": {"name": "z", "version": "1"}}
    del data[missing]
    with pytest.raises(ValueError):
        emit_toml(data)
